# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from belvo_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    _API_LINKS = "/api/links"
    _API_LINKS_ID = "/api/links/{id}"
    _API_ACCOUNTS = "/api/accounts"
    _API_ACCOUNTS_ID = "/api/accounts/{id}"
    _API_TRANSACTIONS = "/api/transactions"
    _API_TRANSACTIONS_ID = "/api/transactions/{id}"
    _API_BALANCES = "/api/balances"
    _API_BALANCES_ID = "/api/balances/{id}"
    _API_INSTITUTIONS = "/api/institutions"
    _API_INSTITUTIONS_ID = "/api/institutions/{id}"
    _API_OWNERS = "/api/owners"
    _API_OWNERS_ID = "/api/owners/{id}"
    _API_INVOICES = "/api/invoices"
    _API_INVOICES_ID = "/api/invoices/{id}"
    _API_TAXRETURNS = "/api/tax-returns"
    _API_TAXRETURNS_ID = "/api/tax-returns/{id}"
    _API_TAXSTATUS = "/api/tax-status"
    _API_TAXSTATUS_ID = "/api/tax-status/{id}"
    _API_TAXCOMPLIANCESTATUS = "/api/tax-compliance-status"
    _API_TAXCOMPLIANCESTATUS_ID = "/api/tax-compliance-status/{id}"
    _API_INCOMES = "/api/incomes"
    _API_INCOMES_ID = "/api/incomes/{id}"
    _API_RECURRINGEXPENSES = "/api/recurring-expenses"
    _API_RECURRINGEXPENSES_ID = "/api/recurring-expenses/{id}"
    _INVESTMENTS_PORTFOLIOS = "/investments/portfolios"
    _INVESTMENTS_PORTFOLIOS_ID = "/investments/portfolios/{id}"
    _RECEIVABLES_TRANSACTIONS = "/receivables/transactions"
    _RECEIVABLES_TRANSACTIONS_ID = "/receivables/transactions/{id}"
    _API_RISKINSIGHTS = "/api/risk-insights"
    _API_RISKINSIGHTS_ID = "/api/risk-insights/{id}"
    _API_TAXRETENTIONS = "/api/tax-retentions"
    _API_TAXRETENTIONS_ID = "/api/tax-retentions/{id}"
    _API_TAXDECLARATIONS = "/api/tax-declarations"
    _API_TAXDECLARATIONS_ID = "/api/tax-declarations/{id}"
    _API_EMPLOYMENTRECORDS = "/api/employment-records"
    _API_EMPLOYMENTRECORDS_ID = "/api/employment-records/{id}"
    _API_ENRICH_INCOMES = "/api/enrich/incomes"
    _API_CATEGORIZATION = "/api/categorization"
    _PAYMENTS_SECRETKEYS = "/payments/secret-keys"
    _PAYMENTS_INSTITUTIONS = "/payments/institutions"
    _PAYMENTS_INSTITUTIONS_ID = "/payments/institutions/{id}"
    _PAYMENTS_CUSTOMERS = "/payments/customers"
    _PAYMENTS_CUSTOMERS_ID = "/payments/customers/{id}"
    _PAYMENTS_BANKACCOUNTS = "/payments/bank-accounts"
    _PAYMENTS_BANKACCOUNTS_ID = "/payments/bank-accounts/{id}"
    _PAYMENTS_PAYMENTLINKS = "/payments/payment-links"
    _PAYMENTS_PAYMENTLINKS_ACCESS_TOKEN = "/payments/payment-links/{access_token}"
    _PAYMENTS_PAYMENTINTENTS = "/payments/payment-intents"
    _PAYMENTS_PAYMENTINTENTS_ID = "/payments/payment-intents/{id}"
    _PAYMENTS_TRANSACTIONS = "/payments/transactions"
    _PAYMENTS_TRANSACTIONS_ID = "/payments/transactions/{id}"
